config/routes.rb
Veterinary::Application.routes.draw do
  root :to=>"authentication#sign_in"
  resources :pets

  resources :appointments

  resources :doctors

  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"

end

app/models/pet.rb
class Pet < ActiveRecord::Base
	belongs_to :doctor
	validates :name, :pet_type, :breed, :age, :weight, :last_visit, presence: true
	validates :age, numericality: true
	
	PET_TYPE = ["DOG", "CAT", "BIRD"]
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :pet_type, :breed, :age, :weight, :last_visit, :doctor_id)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :pattern => "[a-zA-Z/s ]{1,35}", :required => true %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.select :pet_type, Pet::PET_TYPE, {}, :required => true %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed, :pattern => "[a-zA-Z/s ]{1,35}", :required => true %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age, :in => 0..50, :required => true %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight, :in => 0..100, :step => 0.1, :required => true %>
  </div>
  <div class="field">
    <%= f.label :last_visit %><br>
    <%= f.date_field :last_visit, :class => "datepicker", :required => true %>
  </div>
  <div class="field">
    <%= f.label :doctor %><br>
    <%= f.collection_select(:doctor_id, Doctor.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
    $(function() {
    $( ".datepicker" ).datepicker();
  });
</script>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Listing pets</h1>
<h4><%= link_to "Doctors", doctors_path, :class => "pull-right" %> <%= link_to "Appointments", appointments_path, :class => "pull-right" %></h4>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Last visit</th>
      <th>Doctor</th>	
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.pet_type %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.age %></td>
        <td><%= pet.weight %></td>
        <td><%= pet.last_visit %></td>
        <td></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pet.pet_type %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pet.weight %>
</p>

<p>
  <strong>Last visit:</strong>
  <%= @pet.last_visit %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @pet.doctor.name %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>