config/routes.rb
Veterinary::Application.routes.draw do
  root :to=>"authentication#sign_in"
  resources :pets

  resources :appointments

  resources :doctors

  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def sign_in
    @user = User.new
  end

  def login
    username_or_email = params[:user][:username]
    password = params[:user][:password]

    if username_or_email.rindex('@')
      email=username_or_email
      user = User.authenticate_by_email(email, password)
    else
      username=username_or_email
      user = User.authenticate_by_username(username, password)
    end

if user
  session[:user_id] = user.id
  flash[:notice] = 'Welcome.'
  redirect_to doctors_url
else
  flash.now[:error] = 'Unknown user. Please check your username and password.'
  render :action => "sign_in"
end
  end

  def new_user
    @user = User.new
  end

  def register
	  @user = User.new(user_params)

	  if @user.valid?
	    @user.save
	    session[:user_id] = @user.id
	    flash[:notice] = 'Welcome.'
	    redirect_to doctors_url
	  else
	    render :action => "new_user"
	  end
  end

  def signed_out
    session[:user_id] = nil
    flash[:notice] = "You have been signed out."
redirect_to :root
  end
 private
def user_params
    params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)
  end
  
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/views/authentication/new_user.html.erb
<p>Sign Up</p>

<%= form_for(@user, :url => new_user_path, html: {role: "form"}) do |f| %>
  <p>
    <%= f.label 'username:' %><br/>
    <%= f.text_field :username %>
    <%= show_field_error(@user, :username) %>
  </p>
  <p>
    <%= f.label 'email:' %><br/>
    <%= f.text_field :email %>
    <%= show_field_error(@user, :email) %>
  </p>
  <p>
    <%= f.label 'password:' %><br/>
    <%= f.password_field :password %>
    <%= show_field_error(@user, :password) %>
  </p>
  <p>
    <%= f.label 'password confirmation:' %><br/>
    <%= f.password_field :password_confirmation %>
    <%= show_field_error(@user, :password_confirmation) %>
  </p>
  <p>
    <%= f.submit 'Sign Up' %>&nbsp;&nbsp;&nbsp;
    <%= f.submit 'Clear Form', :type => 'reset' %>
  </p>
<% end %>

app/views/authentication/sign_in.html.erb
<p>Sign In</p>
<label>Username</label><br>

<input type="text" value= ""><br>

<label>Password</label><br>

<input type="password" value= ""><br>

<%= link_to " Submit",doctors_path %>