config/routes.rb
Veterinary::Application.routes.draw do
  root :to=>"authentication#sign_in"
  resources :pets

  resources :appointments

  resources :doctors

  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	validates :date_of_visit, :pet, :customer, :reason, presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date_of_visit, :pet, :customer, :reason)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_visit %><br>
    <%= f.text_field :date_of_visit, :class => "datepicker", :required =>true %>
  </div>
  <div class="field">
    <%= f.label :pet %><br>
    <%= f.text_field :pet, :required =>true %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer, :required =>true %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason, :required =>true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


   
<script>
    $(function() {
    $( ".datepicker" ).datepicker({ minDate: 0});
  });
</script>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>
<h4><%= link_to "Pets", pets_path, :class => "pull-right" %> <%= link_to "Doctors", doctors_path, :class => "pull-right" %></h4>
<table>
  <thead>
    <tr>
      <th>Date of visit</th>
      <th>Pet</th>
      <th>Customer</th>
      <th>Reason</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date_of_visit %></td>
        <td><%= appointment.pet %></td>
        <td><%= appointment.customer %></td>
        <td><%= appointment.reason %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of visit:</strong>
  <%= @appointment.date_of_visit %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @appointment.pet %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @appointment.customer %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>